name: Google Indexing

on:
  push:
    branches:
      - main
  workflow_dispatch: # This lets you test it manually

jobs:
  indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Google Indexing API Action
        # Using the exact current release tag
        uses: robingenz/action-google-indexing@v1.0.2
        with:
          sitemap-url: https://eticketdeals.com
          google-json-key: ${{ secrets.GOOGLE_JSON_KEY }}
